input {
  beats {
    port => 5044
  }
}

filter {
  # 필요시 필드 정규화/마스킹/지오IP 등 추가
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "matjom-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
